name: Server Updater

on:
  push:
    branches: [ main ]
    
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Tell the server to update
        run: |
          curl -X POST -H "Password: ${{ secrets.UPDATE_PASSWORD }}" https://squiddy.me/update
